# Generated by Django 6.0.3 on 2026-03-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('user_type', models.CharField(choices=[('villager', 'Villager'), ('asha_worker', 'ASHA Worker'), ('admin_phc', 'Admin / PHC'), ('delivery_partner', 'Delivery Partner')], max_length=30)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
