# Generated by Django 6.0.3 on 2026-03-24 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_healthreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthreport',
            name='village',
        ),
        migrations.AddField(
            model_name='healthreport',
            name='latitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthreport',
            name='longitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
